# Generated by Django 5.0.3 on 2024-04-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=20, verbose_name='BEVERAGE_TYPE'),
        ),
    ]
